# Generated by Django 5.0.3 on 2024-03-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Sepal_Length', models.IntegerField()),
                ('Sepal_Width', models.IntegerField()),
                ('Petal_Length', models.IntegerField()),
                ('Petal_Width', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='approvals',
        ),
    ]
